engines:
  rubocop:
    enabled: true
  golint:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
ratings:
  paths:
  - src/**/*.js
exclude_paths:
- dist/**/*
- compile/**/*
- vendors/**/*
- docsrc/**/*
- demos/**/*
- tests/**/*
